### ISSUE TITLE
[Feature Request] Entity/Item Name + Unlocking Technology

### ISSUE THREAD

**Issue by marlowenorthcott** [dewiniaid/FactorioModDeveloperTools#2]
Is there any chance you could add the entities name and which technology unlocks it to the entity information panel?

Thank you for your work!

**Comment by dewiniaid** [comment]
Entity name should already be appearing in the information panel.

I'll look at adding unlocking technologies in the next update.

**Comment by dewiniaid** [comment]
Added unlocking technologies.
